#!/usr/bin/env python3
"""Validate repository skills and deterministically aggregate their bodies."""

import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import sys
import tempfile


MARKER = "<!-- Generated by ZhouYiLab skills aggregator; edit skills/*/SKILL.md. -->"
NAME = re.compile(r"[a-z0-9]+(?:-[a-z0-9]+)*\Z")
COMMAND = "python skills/zhouyilab-skill-maintenance/scripts/generate_agents.py"


class SpecificationError(ValueError):
    """The source specification is incomplete or unsafe to aggregate."""


def regular_file(path: Path) -> None:
    """Reject links, including dangling links, before reading a source file."""
    if path.is_symlink() or not path.is_file():
        raise SpecificationError(f"Expected a regular non-symlink file: {path}")


def read_skill(path: Path, expected_name: str) -> tuple[str, str]:
    """Parse the deliberately limited name/description frontmatter contract."""
    regular_file(path)
    source = path.read_text(encoding="utf-8-sig").replace("\r\n", "\n")
    lines = source.splitlines()
    if not lines or lines[0] != "---":
        raise SpecificationError(f"Missing frontmatter: {path}")
    try:
        end = lines.index("---", 1)
    except ValueError as error:
        raise SpecificationError(f"Unclosed frontmatter: {path}") from error
    metadata = {}
    for line in lines[1:end]:
        key, separator, value = line.partition(":")
        value = value.strip()
        if not separator or key not in ("name", "description") or key in metadata:
            raise SpecificationError(f"Unsupported or duplicate metadata: {path}: {line}")
        if value.startswith('"'):
            value = json.loads(value)
        elif value.startswith(("'", "|", ">", "[", "{", "&", "*", "!", "#")):
            raise SpecificationError(f"Use plain text or a double-quoted scalar: {path}")
        if not isinstance(value, str) or not value.strip() or "\n" in value or "\r" in value:
            raise SpecificationError(f"Expected nonempty single-line metadata: {path}")
        metadata[key] = value
    if set(metadata) != {"name", "description"} or metadata["name"] != expected_name:
        raise SpecificationError(f"Required name/description or directory name mismatch: {path}")
    body = "\n".join(lines[end + 1:]).strip()
    if not body or re.search(r"^#\s", body, re.MULTILINE):
        raise SpecificationError(f"Body must be nonempty with headings below H1: {path}")
    return metadata["description"], body


def render(root: Path) -> bytes:
    """Validate every input before producing UTF-8/LF output without timestamps."""
    root = root.resolve()
    skills = root / "skills"
    if skills.is_symlink() or not skills.is_dir():
        raise SpecificationError(f"Expected a non-symlink skills directory: {skills}")
    manifest_path = skills / "manifest.json"
    regular_file(manifest_path)
    manifest = json.loads(manifest_path.read_text(encoding="utf-8-sig"))
    if (not isinstance(manifest, dict) or set(manifest) != {"version", "skills"}
            or type(manifest["version"]) is not int or manifest["version"] != 1):
        raise SpecificationError("Expected manifest version 1 with only version/skills keys")
    names = manifest["skills"]
    if not isinstance(names, list) or not names:
        raise SpecificationError("Manifest skills must be a nonempty list")
    for name in names:
        if not isinstance(name, str) or len(name) > 64 or not NAME.fullmatch(name):
            raise SpecificationError(f"Invalid skill directory name: {name!r}")
    if len(set(names)) != len(names):
        raise SpecificationError("Duplicate skills in manifest")
    discovered = {path.parent.name for path in skills.glob("*/SKILL.md")}
    if discovered != set(names):
        raise SpecificationError(
            f"Manifest mismatch; missing files: {sorted(set(names) - discovered)}; "
            f"unlisted skills: {sorted(discovered - set(names))}")

    records = []
    for name in names:
        folder = skills / name
        if folder.is_symlink() or folder.resolve().parent != skills.resolve():
            raise SpecificationError(f"Skill directory escapes source root: {folder}")
        description, body = read_skill(folder / "SKILL.md", name)
        body = rebase_references(folder, name, body)
        records.append((name, description, body))
    # Hash normalized semantic inputs, not line endings or JSON indentation.
    digest = hashlib.sha256(json.dumps(records, ensure_ascii=False).encode("utf-8")).hexdigest()
    sections = [
        MARKER,
        f"<!-- Source SHA256: {digest} -->",
        "# ZhouYiLab 项目规范与模块使用导航",
        "本文件由 `skills/manifest.json` 中的项目 skills 按顺序聚合。"
        "编辑源文件后重新生成，不直接修改本文件。规则按当前任务所涉及的职责适用；"
        "调用模块时阅读对应使用 skill 链接的指南，参考正文不在此展开。",
        f"生成：`{COMMAND}`；只读校验：`{COMMAND} --check`。",
        "## 规范来源",
        "\n".join(f"- [{name}](skills/{name}/SKILL.md)：{description}"
                  for name, description, _ in records),
    ]
    for name, _, body in records:
        sections.extend(["---", f"<!-- Source: skills/{name}/SKILL.md -->", body])
    return ("\n\n".join(sections) + "\n").encode("utf-8")


def rebase_references(folder: Path, name: str, body: str) -> str:
    """Validate simple skill-local reference links and rebase them for root AGENTS."""
    def replace(match):
        relative = match.group(1)
        parts = relative.split("/")
        if any(part in ("", ".", "..") for part in parts) or "\\" in relative:
            raise SpecificationError(f"Invalid reference path: {relative}")
        target = folder.joinpath(*parts)
        for index in range(1, len(parts) + 1):
            if folder.joinpath(*parts[:index]).is_symlink():
                raise SpecificationError(f"Symlink reference: {relative}")
        if folder.resolve() not in target.resolve().parents:
            raise SpecificationError(f"Reference escapes skill: {relative}")
        regular_file(target)
        return f"](skills/{name}/{relative})"

    # Supported contract: inline Markdown links to references/ with no title/anchor.
    # Keep illustrative links inside inline code and fenced examples unchanged.
    sections = re.split(r"(```[\s\S]*?```|`[^`\n]*`)", body)
    return "".join(
        section if index % 2 else re.sub(r"\]\((references/[^)]+)\)", replace, section)
        for index, section in enumerate(sections)
    )


def generate(root: Path, check: bool = False) -> bool:
    """Return whether output matches; check mode never creates or updates files."""
    content = render(root)
    output = root / "AGENTS.md"
    if output.is_symlink():
        raise SpecificationError(f"Refusing symlink output: {output}")
    current = output.read_bytes() if output.exists() else None
    if check:
        return current == content
    if current == content:
        return True
    if current is not None and current.decode("utf-8-sig").splitlines()[:1] != [MARKER]:
        raise SpecificationError("Refusing to overwrite unmanaged AGENTS.md; migrate its rules first")
    # The temporary file stays on the destination filesystem for atomic replace.
    descriptor, temporary = tempfile.mkstemp(prefix="AGENTS-", suffix=".tmp", dir=root)
    try:
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(content)
        os.replace(temporary, output)
    finally:
        Path(temporary).unlink(missing_ok=True)
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Read-only drift check; nonzero on mismatch")
    arguments = parser.parse_args()
    root = Path(__file__).resolve().parents[3]
    try:
        if not generate(root, arguments.check):
            print(f"AGENTS.md is missing or stale. Run: {COMMAND}", file=sys.stderr)
            return 1
    except (OSError, ValueError) as error:
        print(f"Cannot aggregate skills: {error}", file=sys.stderr)
        return 2
    print("AGENTS.md is synchronized." if arguments.check else "AGENTS.md generated (or already synchronized).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
